server:
  port: 8080 # 게이트웨이가 실행될 포트

spring:
  application:
    name: gi-gateway
  cloud:
    gateway:
      routes:
        # 로그인 서비스 라우팅
        - id: login_route
          uri: http://localhost:8081 # 로그인 모듈이 실행되는 주소
          predicates:
            - Path=/api/login/** # /api/login으로 시작하는 모든 요청을 매칭
          filters:
            - StripPrefix=1 # /api/login/abc -> /login/abc (필요에 따라)
            - AddRequestHeader=X-Source, Gateway # 요청 헤더 추가 예시

        # 등록 서비스 라우팅
        - id: register_route
          uri: http://localhost:8082 # 등록 모듈이 실행되는 주소
          predicates:
            - Path=/api/register/**
          filters:
            - StripPrefix=1

        # 검색 서비스 라우팅
        - id: search_route
          uri: http://localhost:8083 # 검색 모듈이 실행되는 주소
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=1

        # 기타 서비스 라우팅 (예시: 모든 API 요청을 특정 API 서버로)
        - id: api_general_route
          uri: lb://API-SERVICE # Eureka 같은 서비스 디스커버리에 등록된 서비스명
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment} # /api/v1/users -> /v1/users

# Eureka Discovery Client 설정 (서비스 디스커버리 사용할 경우)
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/