server:
  port: 8080 # 게이트웨이가 실행될 포트

spring:
  application:
    name: vims-gateway
  cloud:
    gateway:
      default-filters :
        - AuthorizationHeaderFilter
      routes:
        # NOTE: 정적 파일 라우팅 (common, assets)
        - id: vims-login-static-common
          uri: http://localhost:8081
          predicates:
            - Path=/common/**
          filters:
            - AddRequestHeader=X-Source, Gateway

        - id: vims-login-static-assets
          uri: http://localhost:8081
          predicates:
            - Path=/assets/**
          filters:
            - AddRequestHeader=X-Source, Gateway

        # NOTE: 로그인 서비스의 기본 페이지
        - id: vims-login_route
          uri: http://localhost:8081
          predicates:
            - Path=/
          filters:
            - AddRequestHeader=X-Source, Gateway

        # NOTE: 로그인 서비스의 API 라우팅
        - id: vims-login_api_route
          uri: http://localhost:8081
          predicates:
            - Path=/login/**, /api/v1/auth/logout
          filters:
            - AddRequestHeader=X-Source, Gateway
            - name: RewriteLocationResponseHeader
              args:
                  name: Location
                  rewrite-uri: http://localhost:8080/
                  strip-version: NEVER_STRIP

#        # 등록 서비스 라우팅
#        - id: vims-registration_route
#          uri: http://localhost:8082 # 등록 모듈이 실행되는 주소
#          predicates:
#            - Path=/api/register/**
#          filters:
#            - StripPrefix=1

#        # NOTE: 시스템관리 서비스 라우팅 (cms)
        - id: vims-management_route
          uri: http://localhost:8083 # 포트 번호가 누락되어 8083으로 되어 있습니다. 올바른 포트 번호로 수정하세요.
          predicates:
            - Path=/cms/**
          filters:
            - AddRequestHeader=X-Source, Gateway
            - name: RewriteLocationResponseHeader
              args:
                name: Location
                rewrite-uri: http://localhost:8080/
                strip-version: NEVER_STRIP

#
#        # 검사 서비스 라우팅
#        - id: vims-inspection_route
#          uri: lb://API-SERVICE # Eureka 같은 서비스 디스커버리에 등록된 서비스명
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/(?<segment>.*), /${segment} # /api/v1/users -> /v1/users
#
#        # 통계 서비스 라우팅
#        - id: vims-statistics_route
#          uri: http://localhost:8083 # 검색 모듈이 실행되는 주소
#          predicates:
#            - Path=/api/search/**
#          filters:
#            - StripPrefix=1